# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alkomat.ui'
#
# Created: Mon Feb 22 13:33:08 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(640, 480)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(430, 370, 85, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(550, 60, 51, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(327, 60, 211, 221))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.Wino_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Wino_ilosc.setObjectName(_fromUtf8("Wino_ilosc"))
        self.verticalLayout_4.addWidget(self.Wino_ilosc)
        self.Wodka_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Wodka_ilosc.setObjectName(_fromUtf8("Wodka_ilosc"))
        self.verticalLayout_4.addWidget(self.Wodka_ilosc)
        self.Inne_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Inne_ilosc.setObjectName(_fromUtf8("Inne_ilosc"))
        self.verticalLayout_4.addWidget(self.Inne_ilosc)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 30, 271, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(33, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 251, 361))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plec_wybor = QtGui.QComboBox(self.layoutWidget3)
        self.plec_wybor.setObjectName(_fromUtf8("plec_wybor"))
        self.plec_wybor.addItem(_fromUtf8(""))
        self.plec_wybor.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.plec_wybor)
        self.wzrost = QtGui.QSpinBox(self.layoutWidget3)
        self.wzrost.setObjectName(_fromUtf8("wzrost"))
        self.verticalLayout_2.addWidget(self.wzrost)
        self.masa = QtGui.QSpinBox(self.layoutWidget3)
        self.masa.setObjectName(_fromUtf8("masa"))
        self.verticalLayout_2.addWidget(self.masa)
        self.czas_picia = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.czas_picia.setObjectName(_fromUtf8("czas_picia"))
        self.verticalLayout_2.addWidget(self.czas_picia)
        self.zoladek_picie = QtGui.QComboBox(self.layoutWidget3)
        self.zoladek_picie.setObjectName(_fromUtf8("zoladek_picie"))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.zoladek_picie)
        self.comboBox = QtGui.QComboBox(self.layoutWidget3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton.setText(_translate("Dialog", "Licz!", None))
        self.lineEdit_2.setText(_translate("Dialog", "4.9", None))
        self.lineEdit_3.setText(_translate("Dialog", "14", None))
        self.lineEdit_4.setText(_translate("Dialog", "40", None))
        self.label_9.setText(_translate("Dialog", "Piwo:", None))
        self.label_10.setText(_translate("Dialog", "Wino:", None))
        self.label_11.setText(_translate("Dialog", "Wódka:", None))
        self.label_12.setText(_translate("Dialog", "Inne:", None))
        self.label_8.setText(_translate("Dialog", "Spożyłem:", None))
        self.label_13.setText(_translate("Dialog", "W ilości:", None))
        self.label_14.setText(_translate("Dialog", "% Alk.", None))
        self.label.setText(_translate("Dialog", "Jestem:", None))
        self.label_2.setText(_translate("Dialog", "Mierzę:", None))
        self.label_3.setText(_translate("Dialog", "Ważę:", None))
        self.label_4.setText(_translate("Dialog", "Piłem przez:", None))
        self.label_5.setText(_translate("Dialog", "Piłem na:", None))
        self.label_6.setText(_translate("Dialog", "Piłem w:", None))
        self.plec_wybor.setItemText(0, _translate("Dialog", "mężczyzną", None))
        self.plec_wybor.setItemText(1, _translate("Dialog", "kobietą", None))
        self.zoladek_picie.setItemText(0, _translate("Dialog", "pusty żołądek", None))
        self.zoladek_picie.setItemText(1, _translate("Dialog", "w pół pełny żołądek", None))
        self.zoladek_picie.setItemText(2, _translate("Dialog", "pełny żołądek", None))
        self.comboBox.setItemText(0, _translate("Dialog", "domu", None))
        self.comboBox.setItemText(1, _translate("Dialog", "plenerze", None))
        self.comboBox.setItemText(2, _translate("Dialog", "barze", None))
        self.label_7.setText(_translate("Dialog", "Otrzymałem mandat w wysokości:", None))

