# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alkomat.ui'
#
# Created: Mon Feb 22 16:47:14 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(640, 480)
        self.licz_button = QtGui.QPushButton(Dialog)
        self.licz_button.setGeometry(QtCore.QRect(430, 370, 85, 27))
        self.licz_button.setObjectName(_fromUtf8("licz_button"))
	self.licz_button.setEnabled(False)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(550, 80, 51, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.piwo_procent = QtGui.QLineEdit(self.layoutWidget)
        self.piwo_procent.setObjectName(_fromUtf8("piwo_procent"))
        self.verticalLayout_5.addWidget(self.piwo_procent)
        self.wino_procent = QtGui.QLineEdit(self.layoutWidget)
        self.wino_procent.setObjectName(_fromUtf8("wino_procent"))
        self.verticalLayout_5.addWidget(self.wino_procent)
        self.wodka_procent = QtGui.QLineEdit(self.layoutWidget)
        self.wodka_procent.setObjectName(_fromUtf8("wodka_procent"))
        self.verticalLayout_5.addWidget(self.wodka_procent)
        self.inne_procent = QtGui.QLineEdit(self.layoutWidget)
        self.inne_procent.setObjectName(_fromUtf8("inne_procent"))
        self.verticalLayout_5.addWidget(self.inne_procent)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(330, 80, 211, 221))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Piwo_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Piwo_ilosc.setObjectName(_fromUtf8("Piwo_ilosc"))
        self.verticalLayout_4.addWidget(self.Piwo_ilosc)
        self.Wino_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Wino_ilosc.setObjectName(_fromUtf8("Wino_ilosc"))
        self.verticalLayout_4.addWidget(self.Wino_ilosc)
        self.Wodka_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Wodka_ilosc.setObjectName(_fromUtf8("Wodka_ilosc"))
        self.verticalLayout_4.addWidget(self.Wodka_ilosc)
        self.Inne_ilosc = QtGui.QLineEdit(self.layoutWidget1)
        self.Inne_ilosc.setObjectName(_fromUtf8("Inne_ilosc"))
        self.verticalLayout_4.addWidget(self.Inne_ilosc)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 40, 271, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(33, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 40, 285, 381))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plec_wybor = QtGui.QComboBox(self.layoutWidget3)
        self.plec_wybor.setObjectName(_fromUtf8("plec_wybor"))
        self.plec_wybor.addItem(_fromUtf8(""))
        self.plec_wybor.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.plec_wybor)
        self.wzrost = QtGui.QSpinBox(self.layoutWidget3)
        self.wzrost.setMaximum(299)
        self.wzrost.setObjectName(_fromUtf8("wzrost"))
        self.verticalLayout_2.addWidget(self.wzrost)
        self.masa = QtGui.QSpinBox(self.layoutWidget3)
        self.masa.setMaximum(299)
        self.masa.setObjectName(_fromUtf8("masa"))
        self.verticalLayout_2.addWidget(self.masa)
        self.czas_picia = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.czas_picia.setMaximum(72.0)
        self.czas_picia.setObjectName(_fromUtf8("czas_picia"))
        self.verticalLayout_2.addWidget(self.czas_picia)
        self.zoladek_picie = QtGui.QComboBox(self.layoutWidget3)
        self.zoladek_picie.setObjectName(_fromUtf8("zoladek_picie"))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.zoladek_picie.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.zoladek_picie)
        self.gdzie_box = QtGui.QComboBox(self.layoutWidget3)
        self.gdzie_box.setObjectName(_fromUtf8("gdzie_box"))
        self.gdzie_box.addItem(_fromUtf8(""))
        self.gdzie_box.addItem(_fromUtf8(""))
        self.gdzie_box.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.gdzie_box)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.mandat_box = QtGui.QSpinBox(self.layoutWidget3)
        self.mandat_box.setMaximum(9999)
        self.mandat_box.setObjectName(_fromUtf8("mandat_box"))
        self.horizontalLayout_4.addWidget(self.mandat_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem4)
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        spacerItem5 = QtGui.QSpacerItem(20, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem5)
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_7.addWidget(self.label_18)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Alkomat - created by Pawel Wisniewski", None))
        self.licz_button.setText(_translate("Dialog", "Licz!", None))
        self.piwo_procent.setText(_translate("Dialog", "4.9", None))
        self.wino_procent.setText(_translate("Dialog", "14", None))
        self.wodka_procent.setText(_translate("Dialog", "40", None))
        self.label_9.setText(_translate("Dialog", "Piwo:", None))
        self.label_10.setText(_translate("Dialog", "Wino:", None))
        self.label_11.setText(_translate("Dialog", "Wódka:", None))
        self.label_12.setText(_translate("Dialog", "Inne:", None))
        self.label_8.setText(_translate("Dialog", "Spożyłem:", None))
        self.label_13.setText(_translate("Dialog", "W ilości (ml):", None))
        self.label_14.setText(_translate("Dialog", "% Alk.", None))
        self.label_19.setText(_translate("Dialog", "Elektroniczny Alkomat", None))
        self.label.setText(_translate("Dialog", "Jestem:", None))
        self.label_2.setText(_translate("Dialog", "Mierzę:", None))
        self.label_3.setText(_translate("Dialog", "Ważę:", None))
        self.label_4.setText(_translate("Dialog", "Piłem przez:", None))
        self.label_5.setText(_translate("Dialog", "Piłem na:", None))
        self.label_6.setText(_translate("Dialog", "Piłem w:", None))
        self.plec_wybor.setItemText(0, _translate("Dialog", "mężczyzną", None))
        self.plec_wybor.setItemText(1, _translate("Dialog", "kobietą", None))
        self.zoladek_picie.setItemText(0, _translate("Dialog", "pusty żołądek", None))
        self.zoladek_picie.setItemText(1, _translate("Dialog", "w pół pełny żołądek", None))
        self.zoladek_picie.setItemText(2, _translate("Dialog", "pełny żołądek", None))
        self.gdzie_box.setItemText(0, _translate("Dialog", "domu", None))
        self.gdzie_box.setItemText(1, _translate("Dialog", "plenerze", None))
        self.gdzie_box.setItemText(2, _translate("Dialog", "barze", None))
        self.label_7.setText(_translate("Dialog", "Otrzymałem mandat w wysokości:", None))
        self.label_16.setText(_translate("Dialog", "cm", None))
        self.label_15.setText(_translate("Dialog", "kg", None))
        self.label_17.setText(_translate("Dialog", "h", None))
        self.label_18.setText(_translate("Dialog", "zł", None))

